apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec:
  template:
    metadata:
      name: nginx-deploy
      labels:
        env: demo
    spec:      
      containers:
      - image: nginx:latest
        name: nginx-pod
  replicas: 2
  selector:
    matchLabels:
      env: demo