apiVersion: batch/v1
kind: CronJob
metadata: 
  name: democronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
           - name: democronjob
             image: busybox:1.28
             command:
               - /bin/sh
               - -c 
               - date; echo AA MERI JAAN
          restartPolicy: OnFailure