apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
   type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/home/palay/day1"