apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      app: nginx

---

apiVersion: v1
kind: Service
metadata:
 name: nginx-deployment
 labels:
   app: nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
  selector:
    app: nginx
