apiVersion: v1
kind: Pod
metadata: 
  name: affinity-pod-new
spec:
  containers:
   - image: redis
     name: redis
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disk
            operator: In
            values:
            - hdd