apiVersion: v1
kind: Pod
metadata: 
  name: affinity-pod
spec:
  containers:
   - image: nginx
     name: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disk
            operator: In
            values:
            - ssh
          