apiVersion: v1
kind: Pod
metadata:
  name: sidecar-example
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/shared
    # Expose logs from the sidecar for debugging
    command: ["/bin/sh", "-c"]
    args: ["while true; do cat /var/log/shared/logs.txt; sleep 10; done;"]

  - name: busybox-container
    image: busybox:latest
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/shared
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          echo "$(date) - Log entry from the sidecar" >> /var/log/shared/logs.txt;
          sleep 5;
        done;
    
