# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: palaymoundekar/application:1.0
        ports:
        - containerPort: 5771
        env:
        - name: DATABASE_URL
          value: "postgresql://admin:palay@192.168.1.94:5432/palay?schema=nira"  # Remote DB URL
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  selector:
    app: application
  ports:
  - protocol: TCP
    port: 5771
    targetPort: 5771
    nodePort: 30007  
  type: NodePort
