# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentatio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presentation
  template:
    metadata:
      labels:
        app: presentation
    spec:
      containers:
      - name: presentation
        image: palaymoundekar/presentation:3.0
        ports:
        - containerPort: 80
                
---

apiVersion: v1
kind: Service
metadata:
  name: presentation-service
spec:
  selector:
    app: presentation
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001  # You can specify a NodePort or let Kubernetes assign one (range: 30000-32767)
  type: NodePort
