apiVersion: v1
kind: Pod
metadata:
  name: request-limit
  namespace: memory
spec: 
  containers:
   - name: menory-demo
     image: polinux/stress
     resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "128Mi"
     command: ["stress"]
     args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]
     
        