apiVersion: v1
kind: Service
metadata:
  name: verdaccio-service
  labels:
    env: dev
spec:
  type: NodePort
  ports:
    - targetPort: 4873
      port: 4873
      nodePort: 30007
  selector:
    env: dev